[package]
name = "kernel"
version = "0.1.0"
authors = ["Luuk van Oijen <lazyluuk.channel@gmail.com>"]
edition = "2018"

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
